version: '3.8'

services:
  app:
    build: .
    volumes:
      - /Users/erikmelqonyan/repos/aca/deep_dive_lessons/:/app
    working_dir: /app
    stdin_open: true  # Equivalent to -i
    tty: true         # Equivalent to -t
